version: "3.5"
services:

  apache_api:
    build:
      context: .
      dockerfile: 'Dockerfile.mac.dev'

    depends_on:
      - db

    restart: on-failure

    ports:
      - "8000:80"

    environment:
      - DOCKERHOST=${DOCKERHOST}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}

    networks:
      - djangohab

  redis:
    image: redis:7.0.5
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - djangohab

  db:
    image: "timescale/timescaledb:2.8.1-pg12"
    container_name: "db"
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cloud_db
      - TIMESCALEDB_TELEMETRY=off
    ports:
      - "5432:5432"
    networks:
      - djangohab
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  db_data:
    external: false

networks:
  djangohab:
    name: djangohab_default
    driver: bridge
    # Just to work together with the client network
    driver_opts:
      com.docker.network.driver.mtu: 1440
